// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// How probes are sent.
enum ProtocolMessage {
  tcp,
  udp,
  icmp,
}

/// Whether the session watches the internet or the local gateway.
enum KindMessage {
  internet,
  gateway,
}

/// The interface a session is running over.
enum InterfaceTypeMessage {
  ethernet,
  wifi,
  cellular5g,
  cellular4g,
  cellular3g,
  cellular2g,
  cellular,
  vpn,
  other,
  none,
  unknown,
}

/// How a single probe ended.
enum OutcomeMessage {
  success,
  timeout,
  unreachable,
  error,
}

/// What to probe, how, and how often.
class MonitorConfigMessage {
  MonitorConfigMessage({
    required this.probeProtocol,
    required this.kind,
    this.targetIPv4,
    this.fallbackIPv4,
    this.targetName,
    required this.port,
    required this.probeIntervalMillis,
    required this.probeTimeoutMillis,
  });

  /// Named probeProtocol, not protocol: `protocol` is a reserved word in
  /// Swift, and pigeon emits it unescaped.
  ProtocolMessage probeProtocol;

  KindMessage kind;

  /// Null for a gateway monitor, whose target is discovered natively.
  String? targetIPv4;

  /// An alternative address to fall back to after repeated failures.
  String? fallbackIPv4;

  String? targetName;

  int port;

  int probeIntervalMillis;

  int probeTimeoutMillis;

  List<Object?> _toList() {
    return <Object?>[
      probeProtocol,
      kind,
      targetIPv4,
      fallbackIPv4,
      targetName,
      port,
      probeIntervalMillis,
      probeTimeoutMillis,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MonitorConfigMessage decode(Object result) {
    result as List<Object?>;
    return MonitorConfigMessage(
      probeProtocol: result[0]! as ProtocolMessage,
      kind: result[1]! as KindMessage,
      targetIPv4: result[2] as String?,
      fallbackIPv4: result[3] as String?,
      targetName: result[4] as String?,
      port: result[5]! as int,
      probeIntervalMillis: result[6]! as int,
      probeTimeoutMillis: result[7]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MonitorConfigMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(probeProtocol, other.probeProtocol) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(targetIPv4, other.targetIPv4) &&
        _deepEquals(fallbackIPv4, other.fallbackIPv4) &&
        _deepEquals(targetName, other.targetName) &&
        _deepEquals(port, other.port) &&
        _deepEquals(probeIntervalMillis, other.probeIntervalMillis) &&
        _deepEquals(probeTimeoutMillis, other.probeTimeoutMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MonitorConfigMessage(probeProtocol: $probeProtocol, kind: $kind, targetIPv4: $targetIPv4, fallbackIPv4: $fallbackIPv4, targetName: $targetName, port: $port, probeIntervalMillis: $probeIntervalMillis, probeTimeoutMillis: $probeTimeoutMillis)';
  }
}

/// The facts about a running session.
class SessionDataMessage {
  SessionDataMessage({
    required this.interfaceType,
    required this.probeProtocol,
    required this.kind,
    required this.deviceIpAddress,
    required this.targetAddress,
    required this.targetName,
    required this.startedAtUtcMillis,
  });

  InterfaceTypeMessage interfaceType;

  /// Named probeProtocol, not protocol: `protocol` is a reserved word in
  /// Swift, and pigeon emits it unescaped.
  ProtocolMessage probeProtocol;

  KindMessage kind;

  String deviceIpAddress;

  String targetAddress;

  String targetName;

  /// The only wall clock on the wire; every elapsed value is monotonic.
  int startedAtUtcMillis;

  List<Object?> _toList() {
    return <Object?>[
      interfaceType,
      probeProtocol,
      kind,
      deviceIpAddress,
      targetAddress,
      targetName,
      startedAtUtcMillis,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SessionDataMessage decode(Object result) {
    result as List<Object?>;
    return SessionDataMessage(
      interfaceType: result[0]! as InterfaceTypeMessage,
      probeProtocol: result[1]! as ProtocolMessage,
      kind: result[2]! as KindMessage,
      deviceIpAddress: result[3]! as String,
      targetAddress: result[4]! as String,
      targetName: result[5]! as String,
      startedAtUtcMillis: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionDataMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(interfaceType, other.interfaceType) &&
        _deepEquals(probeProtocol, other.probeProtocol) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(deviceIpAddress, other.deviceIpAddress) &&
        _deepEquals(targetAddress, other.targetAddress) &&
        _deepEquals(targetName, other.targetName) &&
        _deepEquals(startedAtUtcMillis, other.startedAtUtcMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SessionDataMessage(interfaceType: $interfaceType, probeProtocol: $probeProtocol, kind: $kind, deviceIpAddress: $deviceIpAddress, targetAddress: $targetAddress, targetName: $targetName, startedAtUtcMillis: $startedAtUtcMillis)';
  }
}

/// Something the native side observed.
sealed class MonitorSignalMessage {}

/// The result of one probe.
class ProbeSampleMessage extends MonitorSignalMessage {
  ProbeSampleMessage({
    required this.sequence,
    this.roundTripMicros,
    required this.outcome,
    required this.elapsedMicros,
  });

  int sequence;

  /// Monotonic, and null unless the outcome is success.
  int? roundTripMicros;

  OutcomeMessage outcome;

  /// Monotonic time since the session started.
  int elapsedMicros;

  List<Object?> _toList() {
    return <Object?>[
      sequence,
      roundTripMicros,
      outcome,
      elapsedMicros,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ProbeSampleMessage decode(Object result) {
    result as List<Object?>;
    return ProbeSampleMessage(
      sequence: result[0]! as int,
      roundTripMicros: result[1] as int?,
      outcome: result[2]! as OutcomeMessage,
      elapsedMicros: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProbeSampleMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sequence, other.sequence) &&
        _deepEquals(roundTripMicros, other.roundTripMicros) &&
        _deepEquals(outcome, other.outcome) &&
        _deepEquals(elapsedMicros, other.elapsedMicros);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ProbeSampleMessage(sequence: $sequence, roundTripMicros: $roundTripMicros, outcome: $outcome, elapsedMicros: $elapsedMicros)';
  }
}

/// A change in the device's network situation.
class NetworkStateMessage extends MonitorSignalMessage {
  NetworkStateMessage({
    required this.interfaceType,
    this.deviceIpAddress,
    this.targetAddress,
  });

  InterfaceTypeMessage interfaceType;

  String? deviceIpAddress;

  String? targetAddress;

  List<Object?> _toList() {
    return <Object?>[
      interfaceType,
      deviceIpAddress,
      targetAddress,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NetworkStateMessage decode(Object result) {
    result as List<Object?>;
    return NetworkStateMessage(
      interfaceType: result[0]! as InterfaceTypeMessage,
      deviceIpAddress: result[1] as String?,
      targetAddress: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NetworkStateMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(interfaceType, other.interfaceType) &&
        _deepEquals(deviceIpAddress, other.deviceIpAddress) &&
        _deepEquals(targetAddress, other.targetAddress);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NetworkStateMessage(interfaceType: $interfaceType, deviceIpAddress: $deviceIpAddress, targetAddress: $targetAddress)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ProtocolMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is KindMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is InterfaceTypeMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is OutcomeMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is MonitorConfigMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is SessionDataMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is ProbeSampleMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is NetworkStateMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ProtocolMessage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : KindMessage.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : InterfaceTypeMessage.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : OutcomeMessage.values[value];
      case 133:
        return MonitorConfigMessage.decode(readValue(buffer)!);
      case 134:
        return SessionDataMessage.decode(readValue(buffer)!);
      case 135:
        return ProbeSampleMessage.decode(readValue(buffer)!);
      case 136:
        return NetworkStateMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

/// Session control.
class MonitoringHostApi {
  /// Constructor for [MonitoringHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MonitoringHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Starts probing and returns the facts about the new session.
  Future<SessionDataMessage> startSession(MonitorConfigMessage config) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.network_analyzer_android.MonitoringHostApi.startSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as SessionDataMessage;
  }

  /// Stops probing within 500 ms. A no-op when nothing is running.
  Future<void> stopSession() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.network_analyzer_android.MonitoringHostApi.stopSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// The running session, or null when none is running.
  Future<SessionDataMessage?> currentSession() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.network_analyzer_android.MonitoringHostApi.currentSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as SessionDataMessage?;
  }
}

/// The single signal stream.
///
/// Pigeon forbids parameters on event-channel methods and requires them all
/// to live in one class, so configuration travels via [MonitoringHostApi]
/// instead and the two signal kinds share one channel through a sealed
/// union.
/// Returns a broadcast [Stream] of events from the `streamMonitorSignals` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<MonitorSignalMessage> streamMonitorSignals({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamMonitorSignalsChannel = EventChannel(
    'dev.flutter.pigeon.network_analyzer_android.MonitoringEventApi.streamMonitorSignals$instanceName',
    pigeonMethodCodec,
  );
  return streamMonitorSignalsChannel.receiveBroadcastStream().map((
    dynamic event,
  ) {
    return event as MonitorSignalMessage;
  });
}
