// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MonitoringPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// How probes are sent.
enum ProtocolMessage: Int, CaseIterable {
  case tcp = 0
  case udp = 1
  case icmp = 2
}

/// Whether the session watches the internet or the local gateway.
enum KindMessage: Int, CaseIterable {
  case internet = 0
  case gateway = 1
}

/// The interface a session is running over.
enum InterfaceTypeMessage: Int, CaseIterable {
  case ethernet = 0
  case wifi = 1
  case cellular5g = 2
  case cellular4g = 3
  case cellular3g = 4
  case cellular2g = 5
  case cellular = 6
  case vpn = 7
  case other = 8
  case none = 9
  case unknown = 10
}

/// How a single probe ended.
enum OutcomeMessage: Int, CaseIterable {
  case success = 0
  case timeout = 1
  case unreachable = 2
  case error = 3
}

/// What to probe, how, and how often.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MonitorConfigMessage: Hashable, CustomStringConvertible {
  /// Named probeProtocol, not protocol: `protocol` is a reserved word in
  /// Swift, and pigeon emits it unescaped.
  var probeProtocol: ProtocolMessage
  var kind: KindMessage
  /// Null for a gateway monitor, whose target is discovered natively.
  var targetIPv4: String? = nil
  /// An alternative address to fall back to after repeated failures.
  var fallbackIPv4: String? = nil
  var targetName: String? = nil
  var port: Int64
  var probeIntervalMillis: Int64
  var probeTimeoutMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MonitorConfigMessage? {
    let probeProtocol = pigeonVar_list[0] as! ProtocolMessage
    let kind = pigeonVar_list[1] as! KindMessage
    let targetIPv4: String? = nilOrValue(pigeonVar_list[2])
    let fallbackIPv4: String? = nilOrValue(pigeonVar_list[3])
    let targetName: String? = nilOrValue(pigeonVar_list[4])
    let port = pigeonVar_list[5] as! Int64
    let probeIntervalMillis = pigeonVar_list[6] as! Int64
    let probeTimeoutMillis = pigeonVar_list[7] as! Int64

    return MonitorConfigMessage(
      probeProtocol: probeProtocol,
      kind: kind,
      targetIPv4: targetIPv4,
      fallbackIPv4: fallbackIPv4,
      targetName: targetName,
      port: port,
      probeIntervalMillis: probeIntervalMillis,
      probeTimeoutMillis: probeTimeoutMillis
    )
  }
  func toList() -> [Any?] {
    return [
      probeProtocol,
      kind,
      targetIPv4,
      fallbackIPv4,
      targetName,
      port,
      probeIntervalMillis,
      probeTimeoutMillis,
    ]
  }
  static func == (lhs: MonitorConfigMessage, rhs: MonitorConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MonitoringPigeonInternal.deepEquals(lhs.probeProtocol, rhs.probeProtocol) && MonitoringPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MonitoringPigeonInternal.deepEquals(lhs.targetIPv4, rhs.targetIPv4) && MonitoringPigeonInternal.deepEquals(lhs.fallbackIPv4, rhs.fallbackIPv4) && MonitoringPigeonInternal.deepEquals(lhs.targetName, rhs.targetName) && MonitoringPigeonInternal.deepEquals(lhs.port, rhs.port) && MonitoringPigeonInternal.deepEquals(lhs.probeIntervalMillis, rhs.probeIntervalMillis) && MonitoringPigeonInternal.deepEquals(lhs.probeTimeoutMillis, rhs.probeTimeoutMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MonitorConfigMessage")
    MonitoringPigeonInternal.deepHash(value: probeProtocol, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: targetIPv4, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: fallbackIPv4, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: targetName, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: port, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: probeIntervalMillis, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: probeTimeoutMillis, hasher: &hasher)
  }

  public var description: String {
    return "MonitorConfigMessage(probeProtocol: \(String(describing: probeProtocol)), kind: \(String(describing: kind)), targetIPv4: \(String(describing: targetIPv4)), fallbackIPv4: \(String(describing: fallbackIPv4)), targetName: \(String(describing: targetName)), port: \(String(describing: port)), probeIntervalMillis: \(String(describing: probeIntervalMillis)), probeTimeoutMillis: \(String(describing: probeTimeoutMillis)))"
  }
}

/// The facts about a running session.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SessionDataMessage: Hashable, CustomStringConvertible {
  var interfaceType: InterfaceTypeMessage
  /// Named probeProtocol, not protocol: `protocol` is a reserved word in
  /// Swift, and pigeon emits it unescaped.
  var probeProtocol: ProtocolMessage
  var kind: KindMessage
  var deviceIpAddress: String
  var targetAddress: String
  var targetName: String
  /// The only wall clock on the wire; every elapsed value is monotonic.
  var startedAtUtcMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SessionDataMessage? {
    let interfaceType = pigeonVar_list[0] as! InterfaceTypeMessage
    let probeProtocol = pigeonVar_list[1] as! ProtocolMessage
    let kind = pigeonVar_list[2] as! KindMessage
    let deviceIpAddress = pigeonVar_list[3] as! String
    let targetAddress = pigeonVar_list[4] as! String
    let targetName = pigeonVar_list[5] as! String
    let startedAtUtcMillis = pigeonVar_list[6] as! Int64

    return SessionDataMessage(
      interfaceType: interfaceType,
      probeProtocol: probeProtocol,
      kind: kind,
      deviceIpAddress: deviceIpAddress,
      targetAddress: targetAddress,
      targetName: targetName,
      startedAtUtcMillis: startedAtUtcMillis
    )
  }
  func toList() -> [Any?] {
    return [
      interfaceType,
      probeProtocol,
      kind,
      deviceIpAddress,
      targetAddress,
      targetName,
      startedAtUtcMillis,
    ]
  }
  static func == (lhs: SessionDataMessage, rhs: SessionDataMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MonitoringPigeonInternal.deepEquals(lhs.interfaceType, rhs.interfaceType) && MonitoringPigeonInternal.deepEquals(lhs.probeProtocol, rhs.probeProtocol) && MonitoringPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MonitoringPigeonInternal.deepEquals(lhs.deviceIpAddress, rhs.deviceIpAddress) && MonitoringPigeonInternal.deepEquals(lhs.targetAddress, rhs.targetAddress) && MonitoringPigeonInternal.deepEquals(lhs.targetName, rhs.targetName) && MonitoringPigeonInternal.deepEquals(lhs.startedAtUtcMillis, rhs.startedAtUtcMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SessionDataMessage")
    MonitoringPigeonInternal.deepHash(value: interfaceType, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: probeProtocol, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: deviceIpAddress, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: targetAddress, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: targetName, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: startedAtUtcMillis, hasher: &hasher)
  }

  public var description: String {
    return "SessionDataMessage(interfaceType: \(String(describing: interfaceType)), probeProtocol: \(String(describing: probeProtocol)), kind: \(String(describing: kind)), deviceIpAddress: \(String(describing: deviceIpAddress)), targetAddress: \(String(describing: targetAddress)), targetName: \(String(describing: targetName)), startedAtUtcMillis: \(String(describing: startedAtUtcMillis)))"
  }
}

/// Something the native side observed.
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol MonitorSignalMessage {

}

/// The result of one probe.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ProbeSampleMessage: MonitorSignalMessage {
  var sequence: Int64
  /// Monotonic, and null unless the outcome is success.
  var roundTripMicros: Int64? = nil
  var outcome: OutcomeMessage
  /// Monotonic time since the session started.
  var elapsedMicros: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProbeSampleMessage? {
    let sequence = pigeonVar_list[0] as! Int64
    let roundTripMicros: Int64? = nilOrValue(pigeonVar_list[1])
    let outcome = pigeonVar_list[2] as! OutcomeMessage
    let elapsedMicros = pigeonVar_list[3] as! Int64

    return ProbeSampleMessage(
      sequence: sequence,
      roundTripMicros: roundTripMicros,
      outcome: outcome,
      elapsedMicros: elapsedMicros
    )
  }
  func toList() -> [Any?] {
    return [
      sequence,
      roundTripMicros,
      outcome,
      elapsedMicros,
    ]
  }
  static func == (lhs: ProbeSampleMessage, rhs: ProbeSampleMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MonitoringPigeonInternal.deepEquals(lhs.sequence, rhs.sequence) && MonitoringPigeonInternal.deepEquals(lhs.roundTripMicros, rhs.roundTripMicros) && MonitoringPigeonInternal.deepEquals(lhs.outcome, rhs.outcome) && MonitoringPigeonInternal.deepEquals(lhs.elapsedMicros, rhs.elapsedMicros)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProbeSampleMessage")
    MonitoringPigeonInternal.deepHash(value: sequence, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: roundTripMicros, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: outcome, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: elapsedMicros, hasher: &hasher)
  }

  public var description: String {
    return "ProbeSampleMessage(sequence: \(String(describing: sequence)), roundTripMicros: \(String(describing: roundTripMicros)), outcome: \(String(describing: outcome)), elapsedMicros: \(String(describing: elapsedMicros)))"
  }
}

/// A change in the device's network situation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NetworkStateMessage: MonitorSignalMessage {
  var interfaceType: InterfaceTypeMessage
  var deviceIpAddress: String? = nil
  var targetAddress: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NetworkStateMessage? {
    let interfaceType = pigeonVar_list[0] as! InterfaceTypeMessage
    let deviceIpAddress: String? = nilOrValue(pigeonVar_list[1])
    let targetAddress: String? = nilOrValue(pigeonVar_list[2])

    return NetworkStateMessage(
      interfaceType: interfaceType,
      deviceIpAddress: deviceIpAddress,
      targetAddress: targetAddress
    )
  }
  func toList() -> [Any?] {
    return [
      interfaceType,
      deviceIpAddress,
      targetAddress,
    ]
  }
  static func == (lhs: NetworkStateMessage, rhs: NetworkStateMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MonitoringPigeonInternal.deepEquals(lhs.interfaceType, rhs.interfaceType) && MonitoringPigeonInternal.deepEquals(lhs.deviceIpAddress, rhs.deviceIpAddress) && MonitoringPigeonInternal.deepEquals(lhs.targetAddress, rhs.targetAddress)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NetworkStateMessage")
    MonitoringPigeonInternal.deepHash(value: interfaceType, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: deviceIpAddress, hasher: &hasher)
    MonitoringPigeonInternal.deepHash(value: targetAddress, hasher: &hasher)
  }

  public var description: String {
    return "NetworkStateMessage(interfaceType: \(String(describing: interfaceType)), deviceIpAddress: \(String(describing: deviceIpAddress)), targetAddress: \(String(describing: targetAddress)))"
  }
}

private class MonitoringPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ProtocolMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return InterfaceTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OutcomeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return MonitorConfigMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return SessionDataMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return ProbeSampleMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return NetworkStateMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MonitoringPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ProtocolMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? KindMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? InterfaceTypeMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? OutcomeMessage {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? MonitorConfigMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? SessionDataMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ProbeSampleMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? NetworkStateMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MonitoringPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MonitoringPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MonitoringPigeonCodecWriter(data: data)
  }
}

class MonitoringPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MonitoringPigeonCodec(readerWriter: MonitoringPigeonCodecReaderWriter())
}

var monitoringPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MonitoringPigeonCodecReaderWriter());

/// Session control.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MonitoringHostApi {
  /// Starts probing and returns the facts about the new session.
  func startSession(config: MonitorConfigMessage) throws -> SessionDataMessage
  /// Stops probing within 500 ms. A no-op when nothing is running.
  func stopSession() throws
  /// The running session, or null when none is running.
  func currentSession() throws -> SessionDataMessage?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MonitoringHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MonitoringPigeonCodec.shared }
  /// Sets up an instance of `MonitoringHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MonitoringHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts probing and returns the facts about the new session.
    let startSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.network_analyzer_ios.MonitoringHostApi.startSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! MonitorConfigMessage
        do {
          let result = try api.startSession(config: configArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startSessionChannel.setMessageHandler(nil)
    }
    /// Stops probing within 500 ms. A no-op when nothing is running.
    let stopSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.network_analyzer_ios.MonitoringHostApi.stopSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopSessionChannel.setMessageHandler { _, reply in
        do {
          try api.stopSession()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopSessionChannel.setMessageHandler(nil)
    }
    /// The running session, or null when none is running.
    let currentSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.network_analyzer_ios.MonitoringHostApi.currentSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      currentSessionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.currentSession()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      currentSessionChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// The single signal stream.
///
/// Pigeon forbids parameters on event-channel methods and requires them all
/// to live in one class, so configuration travels via [MonitoringHostApi]
/// instead and the two signal kinds share one channel through a sealed
/// union.
class StreamMonitorSignalsStreamHandler: PigeonEventChannelWrapper<MonitorSignalMessage> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StreamMonitorSignalsStreamHandler) {
    var channelName = "dev.flutter.pigeon.network_analyzer_ios.MonitoringEventApi.streamMonitorSignals"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<MonitorSignalMessage>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: monitoringPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
