// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.koaladevelopments.network_analyzer_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MonitoringPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** How probes are sent. */
enum class ProtocolMessage(val raw: Int) {
  TCP(0),
  UDP(1),
  ICMP(2);

  companion object {
    fun ofRaw(raw: Int): ProtocolMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Whether the session watches the internet or the local gateway. */
enum class KindMessage(val raw: Int) {
  INTERNET(0),
  GATEWAY(1);

  companion object {
    fun ofRaw(raw: Int): KindMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The interface a session is running over. */
enum class InterfaceTypeMessage(val raw: Int) {
  ETHERNET(0),
  WIFI(1),
  CELLULAR5G(2),
  CELLULAR4G(3),
  CELLULAR3G(4),
  CELLULAR2G(5),
  CELLULAR(6),
  VPN(7),
  OTHER(8),
  NONE(9),
  UNKNOWN(10);

  companion object {
    fun ofRaw(raw: Int): InterfaceTypeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** How a single probe ended. */
enum class OutcomeMessage(val raw: Int) {
  SUCCESS(0),
  TIMEOUT(1),
  UNREACHABLE(2),
  ERROR(3);

  companion object {
    fun ofRaw(raw: Int): OutcomeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * What to probe, how, and how often.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MonitorConfigMessage (
  /**
   * Named probeProtocol, not protocol: `protocol` is a reserved word in
   * Swift, and pigeon emits it unescaped.
   */
  val probeProtocol: ProtocolMessage,
  val kind: KindMessage,
  /** Null for a gateway monitor, whose target is discovered natively. */
  val targetIPv4: String? = null,
  /** An alternative address to fall back to after repeated failures. */
  val fallbackIPv4: String? = null,
  val targetName: String? = null,
  val port: Long,
  val probeIntervalMillis: Long,
  val probeTimeoutMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MonitorConfigMessage {
      val probeProtocol = pigeonVar_list[0] as ProtocolMessage
      val kind = pigeonVar_list[1] as KindMessage
      val targetIPv4 = pigeonVar_list[2] as String?
      val fallbackIPv4 = pigeonVar_list[3] as String?
      val targetName = pigeonVar_list[4] as String?
      val port = pigeonVar_list[5] as Long
      val probeIntervalMillis = pigeonVar_list[6] as Long
      val probeTimeoutMillis = pigeonVar_list[7] as Long
      return MonitorConfigMessage(probeProtocol, kind, targetIPv4, fallbackIPv4, targetName, port, probeIntervalMillis, probeTimeoutMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      probeProtocol,
      kind,
      targetIPv4,
      fallbackIPv4,
      targetName,
      port,
      probeIntervalMillis,
      probeTimeoutMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MonitorConfigMessage
    return MonitoringPigeonUtils.deepEquals(this.probeProtocol, other.probeProtocol) && MonitoringPigeonUtils.deepEquals(this.kind, other.kind) && MonitoringPigeonUtils.deepEquals(this.targetIPv4, other.targetIPv4) && MonitoringPigeonUtils.deepEquals(this.fallbackIPv4, other.fallbackIPv4) && MonitoringPigeonUtils.deepEquals(this.targetName, other.targetName) && MonitoringPigeonUtils.deepEquals(this.port, other.port) && MonitoringPigeonUtils.deepEquals(this.probeIntervalMillis, other.probeIntervalMillis) && MonitoringPigeonUtils.deepEquals(this.probeTimeoutMillis, other.probeTimeoutMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.probeProtocol)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.kind)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.targetIPv4)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.fallbackIPv4)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.targetName)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.port)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.probeIntervalMillis)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.probeTimeoutMillis)
    return result
  }
  override fun toString(): String {
    return "MonitorConfigMessage(probeProtocol=$probeProtocol, kind=$kind, targetIPv4=$targetIPv4, fallbackIPv4=$fallbackIPv4, targetName=$targetName, port=$port, probeIntervalMillis=$probeIntervalMillis, probeTimeoutMillis=$probeTimeoutMillis)"
  }
}

/**
 * The facts about a running session.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SessionDataMessage (
  val interfaceType: InterfaceTypeMessage,
  /**
   * Named probeProtocol, not protocol: `protocol` is a reserved word in
   * Swift, and pigeon emits it unescaped.
   */
  val probeProtocol: ProtocolMessage,
  val kind: KindMessage,
  val deviceIpAddress: String,
  val targetAddress: String,
  val targetName: String,
  /** The only wall clock on the wire; every elapsed value is monotonic. */
  val startedAtUtcMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SessionDataMessage {
      val interfaceType = pigeonVar_list[0] as InterfaceTypeMessage
      val probeProtocol = pigeonVar_list[1] as ProtocolMessage
      val kind = pigeonVar_list[2] as KindMessage
      val deviceIpAddress = pigeonVar_list[3] as String
      val targetAddress = pigeonVar_list[4] as String
      val targetName = pigeonVar_list[5] as String
      val startedAtUtcMillis = pigeonVar_list[6] as Long
      return SessionDataMessage(interfaceType, probeProtocol, kind, deviceIpAddress, targetAddress, targetName, startedAtUtcMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      interfaceType,
      probeProtocol,
      kind,
      deviceIpAddress,
      targetAddress,
      targetName,
      startedAtUtcMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SessionDataMessage
    return MonitoringPigeonUtils.deepEquals(this.interfaceType, other.interfaceType) && MonitoringPigeonUtils.deepEquals(this.probeProtocol, other.probeProtocol) && MonitoringPigeonUtils.deepEquals(this.kind, other.kind) && MonitoringPigeonUtils.deepEquals(this.deviceIpAddress, other.deviceIpAddress) && MonitoringPigeonUtils.deepEquals(this.targetAddress, other.targetAddress) && MonitoringPigeonUtils.deepEquals(this.targetName, other.targetName) && MonitoringPigeonUtils.deepEquals(this.startedAtUtcMillis, other.startedAtUtcMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.interfaceType)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.probeProtocol)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.kind)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.deviceIpAddress)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.targetAddress)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.targetName)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.startedAtUtcMillis)
    return result
  }
  override fun toString(): String {
    return "SessionDataMessage(interfaceType=$interfaceType, probeProtocol=$probeProtocol, kind=$kind, deviceIpAddress=$deviceIpAddress, targetAddress=$targetAddress, targetName=$targetName, startedAtUtcMillis=$startedAtUtcMillis)"
  }
}

/**
 * Something the native side observed.
 *
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class MonitorSignalMessage 
/**
 * The result of one probe.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProbeSampleMessage (
  val sequence: Long,
  /** Monotonic, and null unless the outcome is success. */
  val roundTripMicros: Long? = null,
  val outcome: OutcomeMessage,
  /** Monotonic time since the session started. */
  val elapsedMicros: Long
) : MonitorSignalMessage()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProbeSampleMessage {
      val sequence = pigeonVar_list[0] as Long
      val roundTripMicros = pigeonVar_list[1] as Long?
      val outcome = pigeonVar_list[2] as OutcomeMessage
      val elapsedMicros = pigeonVar_list[3] as Long
      return ProbeSampleMessage(sequence, roundTripMicros, outcome, elapsedMicros)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sequence,
      roundTripMicros,
      outcome,
      elapsedMicros,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProbeSampleMessage
    return MonitoringPigeonUtils.deepEquals(this.sequence, other.sequence) && MonitoringPigeonUtils.deepEquals(this.roundTripMicros, other.roundTripMicros) && MonitoringPigeonUtils.deepEquals(this.outcome, other.outcome) && MonitoringPigeonUtils.deepEquals(this.elapsedMicros, other.elapsedMicros)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.sequence)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.roundTripMicros)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.outcome)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.elapsedMicros)
    return result
  }
  override fun toString(): String {
    return "ProbeSampleMessage(sequence=$sequence, roundTripMicros=$roundTripMicros, outcome=$outcome, elapsedMicros=$elapsedMicros)"
  }
}

/**
 * A change in the device's network situation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NetworkStateMessage (
  val interfaceType: InterfaceTypeMessage,
  val deviceIpAddress: String? = null,
  val targetAddress: String? = null
) : MonitorSignalMessage()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NetworkStateMessage {
      val interfaceType = pigeonVar_list[0] as InterfaceTypeMessage
      val deviceIpAddress = pigeonVar_list[1] as String?
      val targetAddress = pigeonVar_list[2] as String?
      return NetworkStateMessage(interfaceType, deviceIpAddress, targetAddress)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      interfaceType,
      deviceIpAddress,
      targetAddress,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NetworkStateMessage
    return MonitoringPigeonUtils.deepEquals(this.interfaceType, other.interfaceType) && MonitoringPigeonUtils.deepEquals(this.deviceIpAddress, other.deviceIpAddress) && MonitoringPigeonUtils.deepEquals(this.targetAddress, other.targetAddress)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.interfaceType)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.deviceIpAddress)
    result = 31 * result + MonitoringPigeonUtils.deepHash(this.targetAddress)
    return result
  }
  override fun toString(): String {
    return "NetworkStateMessage(interfaceType=$interfaceType, deviceIpAddress=$deviceIpAddress, targetAddress=$targetAddress)"
  }
}
private open class MonitoringPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ProtocolMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KindMessage.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          InterfaceTypeMessage.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OutcomeMessage.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MonitorConfigMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SessionDataMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProbeSampleMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NetworkStateMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ProtocolMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is KindMessage -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is InterfaceTypeMessage -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is OutcomeMessage -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is MonitorConfigMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is SessionDataMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ProbeSampleMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is NetworkStateMessage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MonitoringPigeonMethodCodec = StandardMethodCodec(MonitoringPigeonCodec())

/**
 * Session control.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface MonitoringHostApi {
  /** Starts probing and returns the facts about the new session. */
  fun startSession(config: MonitorConfigMessage): SessionDataMessage
  /** Stops probing within 500 ms. A no-op when nothing is running. */
  fun stopSession()
  /** The running session, or null when none is running. */
  fun currentSession(): SessionDataMessage?

  companion object {
    /** The codec used by MonitoringHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MonitoringPigeonCodec()
    }
    /** Sets up an instance of `MonitoringHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MonitoringHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.network_analyzer_android.MonitoringHostApi.startSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as MonitorConfigMessage
            val wrapped: List<Any?> = try {
              listOf(api.startSession(configArg))
            } catch (exception: Throwable) {
              MonitoringPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.network_analyzer_android.MonitoringHostApi.stopSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopSession()
              listOf(null)
            } catch (exception: Throwable) {
              MonitoringPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.network_analyzer_android.MonitoringHostApi.currentSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.currentSession())
            } catch (exception: Throwable) {
              MonitoringPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MonitoringPigeonStreamHandler<T>(
    val wrapper: MonitoringPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MonitoringPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/**
 * The single signal stream.
 *
 * Pigeon forbids parameters on event-channel methods and requires them all
 * to live in one class, so configuration travels via [MonitoringHostApi]
 * instead and the two signal kinds share one channel through a sealed
 * union.
 */
abstract class StreamMonitorSignalsStreamHandler : MonitoringPigeonEventChannelWrapper<MonitorSignalMessage> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamMonitorSignalsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.network_analyzer_android.MonitoringEventApi.streamMonitorSignals"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MonitoringPigeonStreamHandler<MonitorSignalMessage>(streamHandler)
      EventChannel(messenger, channelName, MonitoringPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MonitoringPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<MonitorSignalMessage>) {}

override fun onCancel(p0: Any?) {}
}
      
